version: '3.5'

services:

  api:
    build: .
    container_name: edu-chatbot-api
    image: edu-chatbot-image
    volumes:
      - ./src:/app/src
    ports:
      - "3333:3333"
  
  postgres:
    image: postgres:11.1-alpine
    container_name: edu-chatbot-postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-educhatbot}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}
      - TZ=GMT
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./data:/app/data
      - ./src/database/seed:/app/seed
    ports:
      - 7777:5432

volumes:
  postgres_data: